# basic options
title: SAMACADMINS.COM
author: SAMACADMINS.COM
email: samacadmins@gmail.com
description: San Antonio Mac Admins User Group
twitter_username: samacadmins
github_username:  samacadmins

# Build settings
markdown: kramdown
theme: minima
