# basic options
title: SAMACADMINS.COM
author: fdhernandezjr
email: fdhernandezjr@gmail.com
description: User group for San Antonio Apple administrators
twitter_username: fdhernandezjr
github_username:  fdhernandezjr

# Build settings
markdown: kramdown
theme: jekyll-theme-architect
