# basic options
title: SAMACADMINS.COM
author: fdhernandezjr
email: fdhernandezjr@gmail.com
description: SAMACADMINS.COM
twitter_username: fdhernandezjr
github_username:  fdhernandezjr

# Build settings
markdown: kramdown
theme: minima
